version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
    container_name: genai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/workspace/backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    depends_on:
      - db

  frontend:
    build:
      context: ./src/frontend
    container_name: genai-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/workspace/frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  db:
    image: postgres:13
    container_name: genai-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
