name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Lint Code
      run: |
        flake8 backend/

    - name: Run Tests
      run: |
        pytest backend/tests/

    - name: Build and Push Docker Images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: backend/Dockerfile
        push: true
        tags: your_dockerhub_user/genai-backend:latest

    - name: Deploy to Cloud (optional)
      run: |
        # Add your cloud deployment scripts (e.g., Terraform apply, AWS CLI)
